In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(columns = ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Look at NAME value counts for binning
name_count = application_df['NAME'].value_counts()
name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `names_to_replace`
names_to_replace = list(name_count[name_count <= 5].index)
names_to_replace

#Replace in the dataframe
for name in names_to_replace:
  application_df['NAME'] = application_df['NAME'].replace(name, "Other")

#Confirm that binning was sucessful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [6]:
#Looking at APPLICATION TYPE counts for binning
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
class_count_binning = application_df['CLASSIFICATION'].value_counts()
class_count_binning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = class_count_binning[class_count_binning>1]
classification_counts.head()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count_binning[class_count_binning<1000].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
application_categorical = application_df.dtypes[application_df.dtypes == "object"].index.tolist()

In [12]:
application_categorical

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [13]:
application_with_dummies = pd.get_dummies(application_df)

In [14]:
application_with_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [15]:
# Split our preprocessed data into our features and target arrays
y = application_with_dummies['IS_SUCCESSFUL'].values

# Take out
X = application_with_dummies.drop('IS_SUCCESSFUL', axis = 1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=100
hidden_nodes_layer2=30
hidden_nodes_layer3=10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='sigmoid'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='sigmoid'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               39900

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 43,251
Trainable params: 43,251
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [21]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 4s 6ms/step - loss: 0.4185 - accuracy: 0.8008 - val_loss: 0.4248 - val_accuracy: 0.7976
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4173 - accuracy: 0.8019 - val_loss: 0.4290 - val_accuracy: 0.7984
Epoch 3/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4172 - accuracy: 0.8021 - val_loss: 0.4253 - val_accuracy: 0.7984
Epoch 4/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4163 - accuracy: 0.8027 - val_loss: 0.4301 - val_accuracy: 0.7961
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4151 - accuracy: 0.8029 - val_loss: 0.4290 - val_accuracy: 0.7989
Epoch 6/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4149 - accuracy: 0.8021 - val_loss: 0.4289 - val_accuracy: 0.8015
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4140 - accuracy: 0.8037 - val_loss: 0.4322 - val_accuracy: 0.7971
Epoch 8/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4145 - accuracy: 0.8027 - val_loss: 0.4282 - val_accuracy: 0.7989
Epoch 9/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4132 - accuracy: 0.8027 - val_loss: 0.4315 - val_accuracy: 0.8012
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4125 - accuracy: 0.8037 - val_loss: 0.4303 - val_accuracy: 0.7984
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8038 - val_loss: 0.4295 - val_accuracy: 0.7958
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4116 - accuracy: 0.8031 - val_loss: 0.4305 - val_accuracy: 0.7984
Epoch 13/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4112 - accuracy: 0.8032 - val_loss: 0.4305 - val_accuracy: 0.7974
Epoch 14/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4103 - accuracy: 0.8043 - val_loss: 0.4300 - val_accuracy: 0.7979
Epoch 15/100
684/684 [==============================] - 3s 5ms/step - loss: 0.4101 - accuracy: 0.8040 - val_loss: 0.4304 - val_accuracy: 0.8010
Epoch 16/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4094 - accuracy: 0.8039 - val_loss: 0.4319 - val_accuracy: 0.7974
Epoch 17/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4094 - accuracy: 0.8048 - val_loss: 0.4305 - val_accuracy: 0.7994
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4084 - accuracy: 0.8047 - val_loss: 0.4309 - val_accuracy: 0.7992
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4085 - accuracy: 0.8039 - val_loss: 0.4313 - val_accuracy: 0.7974
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4080 - accuracy: 0.8048 - val_loss: 0.4322 - val_accuracy: 0.8038
Epoch 21/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4074 - accuracy: 0.8057 - val_loss: 0.4298 - val_accuracy: 0.8005
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4068 - accuracy: 0.8066 - val_loss: 0.4341 - val_accuracy: 0.8015
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4071 - accuracy: 0.8055 - val_loss: 0.4329 - val_accuracy: 0.7976
Epoch 24/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4068 - accuracy: 0.8052 - val_loss: 0.4335 - val_accuracy: 0.7979
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8061 - val_loss: 0.4329 - val_accuracy: 0.7984
Epoch 26/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4055 - accuracy: 0.8056 - val_loss: 0.4351 - val_accuracy: 0.7976
Epoch 27/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4052 - accuracy: 0.8054 - val_loss: 0.4392 - val_accuracy: 0.7974
Epoch 28/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4052 - accuracy: 0.8056 - val_loss: 0.4358 - val_accuracy: 0.7968
Epoch 29/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4045 - accuracy: 0.8070 - val_loss: 0.4364 - val_accuracy: 0.7966
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4054 - accuracy: 0.8068 - val_loss: 0.4364 - val_accuracy: 0.7997
Epoch 31/100
684/684 [==============================] - 4s 5ms/step - loss: 0.4044 - accuracy: 0.8067 - val_loss: 0.4374 - val_accuracy: 0.7989
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4041 - accuracy: 0.8061 - val_loss: 0.4372 - val_accuracy: 0.7976
Epoch 33/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4038 - accuracy: 0.8065 - val_loss: 0.4383 - val_accuracy: 0.7979
Epoch 34/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4038 - accuracy: 0.8064 - val_loss: 0.4374 - val_accuracy: 0.7979
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8069 - val_loss: 0.4425 - val_accuracy: 0.7966
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8077 - val_loss: 0.4403 - val_accuracy: 0.7968
Epoch 37/100
684/684 [==============================] - 3s 5ms/step - loss: 0.4029 - accuracy: 0.8071 - val_loss: 0.4403 - val_accuracy: 0.7968
Epoch 38/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8073 - val_loss: 0.4403 - val_accuracy: 0.7971
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8067 - val_loss: 0.4383 - val_accuracy: 0.7976
Epoch 40/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4024 - accuracy: 0.8065 - val_loss: 0.4382 - val_accuracy: 0.7997
Epoch 41/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4021 - accuracy: 0.8075 - val_loss: 0.4403 - val_accuracy: 0.7968
Epoch 42/100
684/684 [==============================] - 4s 5ms/step - loss: 0.4018 - accuracy: 0.8079 - val_loss: 0.4404 - val_accuracy: 0.7968
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8075 - val_loss: 0.4419 - val_accuracy: 0.7976
Epoch 44/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4015 - accuracy: 0.8078 - val_loss: 0.4425 - val_accuracy: 0.7971
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4008 - accuracy: 0.8074 - val_loss: 0.4444 - val_accuracy: 0.7961
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4007 - accuracy: 0.8080 - val_loss: 0.4450 - val_accuracy: 0.7968
Epoch 47/100
684/684 [==============================] - 3s 5ms/step - loss: 0.4009 - accuracy: 0.8077 - val_loss: 0.4445 - val_accuracy: 0.7968
Epoch 48/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4005 - accuracy: 0.8082 - val_loss: 0.4448 - val_accuracy: 0.7974
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4011 - accuracy: 0.8076 - val_loss: 0.4430 - val_accuracy: 0.7963
Epoch 50/100
684/684 [==============================] - 2s 3ms/step - loss: 0.4004 - accuracy: 0.8082 - val_loss: 0.4434 - val_accuracy: 0.7968
Epoch 51/100
684/684 [==============================] - 2s 4ms/step - loss: 0.4002 - accuracy: 0.8079 - val_loss: 0.4443 - val_accuracy: 0.7966
Epoch 52/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3997 - accuracy: 0.8086 - val_loss: 0.4466 - val_accuracy: 0.7968
Epoch 53/100
684/684 [==============================] - 3s 4ms/step - loss: 0.4000 - accuracy: 0.8084 - val_loss: 0.4439 - val_accuracy: 0.7974
Epoch 54/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3995 - accuracy: 0.8086 - val_loss: 0.4475 - val_accuracy: 0.7963
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3994 - accuracy: 0.8086 - val_loss: 0.4458 - val_accuracy: 0.7971
Epoch 56/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3995 - accuracy: 0.8085 - val_loss: 0.4472 - val_accuracy: 0.7979
Epoch 57/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3997 - accuracy: 0.8081 - val_loss: 0.4447 - val_accuracy: 0.7981
Epoch 58/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3992 - accuracy: 0.8084 - val_loss: 0.4463 - val_accuracy: 0.7989
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3994 - accuracy: 0.8086 - val_loss: 0.4484 - val_accuracy: 0.7971
Epoch 60/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3994 - accuracy: 0.8083 - val_loss: 0.4458 - val_accuracy: 0.7966
Epoch 61/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3989 - accuracy: 0.8086 - val_loss: 0.4471 - val_accuracy: 0.7974
Epoch 62/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8089 - val_loss: 0.4482 - val_accuracy: 0.7968
Epoch 63/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3984 - accuracy: 0.8083 - val_loss: 0.4502 - val_accuracy: 0.7958
Epoch 64/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3991 - accuracy: 0.8097 - val_loss: 0.4540 - val_accuracy: 0.7971
Epoch 65/100
684/684 [==============================] - 2s 4ms/step - loss: 0.3987 - accuracy: 0.8088 - val_loss: 0.4505 - val_accuracy: 0.7971
Epoch 66/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8089 - val_loss: 0.4507 - val_accuracy: 0.7955
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8090 - val_loss: 0.4489 - val_accuracy: 0.7966
Epoch 68/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8087 - val_loss: 0.4508 - val_accuracy: 0.7968
Epoch 69/100
684/684 [==============================] - 2s 4ms/step - loss: 0.3982 - accuracy: 0.8090 - val_loss: 0.4526 - val_accuracy: 0.7961
Epoch 70/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8091 - val_loss: 0.4479 - val_accuracy: 0.7981
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3984 - accuracy: 0.8095 - val_loss: 0.4507 - val_accuracy: 0.7966
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8086 - val_loss: 0.4512 - val_accuracy: 0.7968
Epoch 73/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3989 - accuracy: 0.8083 - val_loss: 0.4491 - val_accuracy: 0.8005
Epoch 74/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3986 - accuracy: 0.8095 - val_loss: 0.4526 - val_accuracy: 0.7979
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3985 - accuracy: 0.8092 - val_loss: 0.4520 - val_accuracy: 0.7966
Epoch 76/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3983 - accuracy: 0.8099 - val_loss: 0.4513 - val_accuracy: 0.7963
Epoch 77/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3980 - accuracy: 0.8090 - val_loss: 0.4543 - val_accuracy: 0.7963
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8099 - val_loss: 0.4512 - val_accuracy: 0.7976
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3982 - accuracy: 0.8095 - val_loss: 0.4524 - val_accuracy: 0.7968
Epoch 80/100
684/684 [==============================] - 2s 4ms/step - loss: 0.3977 - accuracy: 0.8096 - val_loss: 0.4534 - val_accuracy: 0.7966
Epoch 81/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3976 - accuracy: 0.8100 - val_loss: 0.4571 - val_accuracy: 0.7971
Epoch 82/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3974 - accuracy: 0.8090 - val_loss: 0.4552 - val_accuracy: 0.7968
Epoch 83/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3979 - accuracy: 0.8095 - val_loss: 0.4534 - val_accuracy: 0.7974
Epoch 84/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8094 - val_loss: 0.4553 - val_accuracy: 0.7968
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3978 - accuracy: 0.8093 - val_loss: 0.4516 - val_accuracy: 0.7963
Epoch 86/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8096 - val_loss: 0.4544 - val_accuracy: 0.7968
Epoch 87/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3976 - accuracy: 0.8099 - val_loss: 0.4544 - val_accuracy: 0.7971
Epoch 88/100
684/684 [==============================] - 2s 4ms/step - loss: 0.3977 - accuracy: 0.8091 - val_loss: 0.4528 - val_accuracy: 0.7971
Epoch 89/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8091 - val_loss: 0.4563 - val_accuracy: 0.7974
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3976 - accuracy: 0.8095 - val_loss: 0.4549 - val_accuracy: 0.7966
Epoch 91/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3972 - accuracy: 0.8101 - val_loss: 0.4536 - val_accuracy: 0.7976
Epoch 92/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3968 - accuracy: 0.8100 - val_loss: 0.4542 - val_accuracy: 0.7974
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3965 - accuracy: 0.8102 - val_loss: 0.4561 - val_accuracy: 0.7974
Epoch 94/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3971 - accuracy: 0.8096 - val_loss: 0.4585 - val_accuracy: 0.7971
Epoch 95/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8101 - val_loss: 0.4575 - val_accuracy: 0.7961
Epoch 96/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8099 - val_loss: 0.4600 - val_accuracy: 0.7950
Epoch 97/100
684/684 [==============================] - 2s 3ms/step - loss: 0.3969 - accuracy: 0.8103 - val_loss: 0.4541 - val_accuracy: 0.7968
Epoch 98/100
684/684 [==============================] - 3s 4ms/step - loss: 0.3969 - accuracy: 0.8100 - val_loss: 0.4569 - val_accuracy: 0.7966
Epoch 99/100
684/684 [==============================] - 3s 5ms/step - loss: 0.3969 - accuracy: 0.8099 - val_loss: 0.4579 - val_accuracy: 0.7955
Epoch 100/100
684/684 [==============================] - 3s 5ms/step - loss: 0.3974 - accuracy: 0.8100 - val_loss: 0.4579 - val_accuracy: 0.7963

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4906 - accuracy: 0.7858 - 495ms/epoch - 2ms/step
Loss: 0.4905915856361389, Accuracy: 0.7857726216316223

In [24]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/AlphabetSoupCharity_Optimization.h5')
files.download('/content/AlphabetSoupCharity_Optimization.h5')